using RouterPilot.Models;
using RouterPilot.Presentation;
using RouterPilot.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.Extensions.DependencyInjection;
using RouterPilot.ViewModels;

static void Require(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
NetworkHealthViewInput Input(DataFreshnessState router = DataFreshnessState.Fresh, DataFreshnessState wan = DataFreshnessState.Fresh, DataFreshnessState adGuardFreshness = DataFreshnessState.Fresh, DataFreshnessState wifi = DataFreshnessState.Fresh, DataFreshnessState dhcp = DataFreshnessState.Fresh, AdGuardAvailabilityState adGuard = AdGuardAvailabilityState.Available, bool includeAdGuard = true, string vpn = "Connected", bool vpnAvailable = true, bool vpnConfigured = true, bool statsLoaded = true, RouterPilotStatus stats = RouterPilotStatus.Active, string cpu = "10%", string temperature = "45 C", string memory = "40%", string storage = "20%", string uptime = "1d", string load = "0.1", string routerFirmwareVersion = "4.6.0", FirmwareUpdateCheckStatus firmwareStatus = FirmwareUpdateCheckStatus.UpToDate) => new(router, wan, adGuardFreshness, DataFreshnessState.Fresh, wifi, dhcp, true, true, "now", "1.2.3.4", "192.168.1.1", "1.1.1.1", adGuard, includeAdGuard, true, true, false, vpnAvailable, vpnConfigured, vpn, "WireGuard", 2, 2, 0, 0, 3, true, 3, 1, cpu, temperature, memory, storage, uptime, load, routerFirmwareVersion, firmwareStatus, statsLoaded, stats, "Existing status.");
NetworkHealthViewSnapshot healthy = NetworkHealthViewProjection.Create(Input());
Require(healthy.OverallStatus == "Healthy", "healthy state");
Require(NetworkHealthViewProjection.Create(Input(DataFreshnessState.Unavailable)).OverallStatus == "Unavailable", "router unavailable");
NetworkHealthViewSnapshot adGuardUnavailable = NetworkHealthViewProjection.Create(Input(adGuard: AdGuardAvailabilityState.Unavailable));
Require(adGuardUnavailable.Checks.Single(x => x.Title == "DNS / AdGuard").Status == "Unavailable" && adGuardUnavailable.OverallStatus == "Attention needed", "AdGuard unavailable");
NetworkHealthViewSnapshot adGuardUnused = NetworkHealthViewProjection.Create(Input(adGuard: AdGuardAvailabilityState.Unavailable, includeAdGuard: false));
Require(adGuardUnused.Checks.Single(x => x.Title == "DNS / AdGuard").Status == "Not in use" && adGuardUnused.OverallStatus == "Healthy", "optional AdGuard is informational");
Require(NetworkHealthViewProjection.Create(Input(adGuardFreshness: DataFreshnessState.Loading)).OverallStatus == "Initializing", "expected AdGuard loading state");
Require(NetworkHealthViewProjection.Create(Input(adGuardFreshness: DataFreshnessState.Loading, includeAdGuard: false)).OverallStatus == "Initializing", "optional AdGuard checking state");
Require(DashboardHealthProjection.Create(new(true, true, false, false, 0, false, 0, 0, false, FirmwareUpdateCheckStatus.UpToDate, string.Empty, string.Empty)).Score == 100, "unused AdGuard is excluded from Dashboard health score");
Require(DashboardHealthProjection.Create(new(true, true, false, true, 0, false, 0, 0, false, FirmwareUpdateCheckStatus.UpToDate, string.Empty, string.Empty)).Score == 85, "expected AdGuard affects Dashboard health score");
NetworkHealthViewSnapshot disconnectedVpn = NetworkHealthViewProjection.Create(Input(vpn: "Disconnected"));
Require(disconnectedVpn.Checks.Single(x => x.Title == "VPN").Status == "Disconnected" && disconnectedVpn.OverallStatus == "Healthy", "VPN disconnected is informational");
Require(NetworkHealthViewProjection.Create(Input(vpnConfigured: false)).OverallStatus == "Healthy", "VPN not configured is informational");
Require(NetworkHealthViewProjection.Create(Input(vpn: "Authentication failed")).OverallStatus == "Attention needed", "VPN explicit failure affects health");
Require(NetworkHealthViewProjection.Create(Input(vpn: "Connection did not complete")).OverallStatus == "Attention needed", "VPN failed tunnel affects health");
Require(NetworkHealthViewProjection.Create(Input(stats: RouterPilotStatus.Disabled)).Checks.Single(x => x.Title == "Data Statistics").Status == "Disabled", "statistics disabled");
Require(NetworkHealthViewProjection.Create(Input(DataFreshnessState.Stale)).Checks.Single(x => x.Title == "Router").Status == "Stale", "stale state");
Require(NetworkHealthViewProjection.Create(Input(statsLoaded: false)).Checks.Single(x => x.Title == "Data Statistics").Status == "Not loaded", "partial state");
Require(NetworkHealthViewProjection.Create(Input(DataFreshnessState.Loading)).OverallStatus == "Initializing", "loading state");
Require(NetworkHealthViewProjection.Create(Input(wifi: DataFreshnessState.Loading)).OverallStatus != "Healthy", "Wi-Fi loading state");
Require(NetworkHealthViewProjection.Create(Input(wifi: DataFreshnessState.Stale)).OverallStatus != "Healthy", "Wi-Fi stale state");
Require(NetworkHealthViewProjection.Create(Input(dhcp: DataFreshnessState.Loading)).OverallStatus != "Healthy", "DHCP loading state");
Require(NetworkHealthViewProjection.Create(Input(wifi: DataFreshnessState.Unavailable)).OverallStatus != "Healthy", "Wi-Fi unavailable state");
Require(NetworkHealthViewProjection.Create(Input() with { WifiActiveRadios = 1, WifiDisabledRadios = 1 }).OverallStatus == "Healthy", "intentionally disabled Wi-Fi radio is informational");
Require(NetworkHealthViewProjection.Create(Input() with { WifiActiveRadios = 0, WifiDisabledRadios = 2 }).OverallStatus == "Healthy", "all intentionally disabled Wi-Fi radios are informational");
Require(NetworkHealthViewProjection.Create(Input(dhcp: DataFreshnessState.Unavailable)).OverallStatus != "Healthy", "DHCP unavailable state");
Require(NetworkHealthViewProjection.Create(Input(cpu: "-", temperature: "-", memory: "-", storage: "-", uptime: "-", load: "-")).Checks.Single(x => x.Title == "Router resources").Status == "Unavailable", "missing resources");
Require(NetworkHealthViewProjection.Create(Input(cpu: "-", temperature: "45 C")).Checks.Single(x => x.Title == "Router resources").Status == "Partial", "partial resources");
Require(NetworkHealthViewProjection.Create(Input(wan: DataFreshnessState.Loading)).OverallStatus != "Healthy", "WAN loading state");
Require(NetworkHealthViewProjection.Create(Input(adGuardFreshness: DataFreshnessState.Loading)).OverallStatus != "Healthy", "AdGuard loading state");
NetworkHealthViewCheck firmwareUpToDate = NetworkHealthViewProjection.Create(Input(routerFirmwareVersion: "4.6.0", firmwareStatus: FirmwareUpdateCheckStatus.UpToDate)).Checks.Single(x => x.Title == "Firmware");
Require(firmwareUpToDate.Status == "Up to date" && firmwareUpToDate.Detail == "Current version: 4.6.0", "GL.iNet firmware up to date");
Require(NetworkHealthViewProjection.Create(Input(firmwareStatus: FirmwareUpdateCheckStatus.UpdateAvailable)).Checks.Single(x => x.Title == "Firmware").Status == "Update available", "GL.iNet firmware update available");
Require(NetworkHealthViewProjection.Create(Input(firmwareStatus: FirmwareUpdateCheckStatus.Pending)).Checks.Single(x => x.Title == "Firmware").Status == "Checking", "GL.iNet firmware checking");
Require(NetworkHealthViewProjection.Create(Input(firmwareStatus: FirmwareUpdateCheckStatus.NotAvailable)).Checks.Single(x => x.Title == "Firmware").Status == "Unavailable", "GL.iNet firmware unavailable");
Require(firmwareUpToDate.NavigationTarget == "maintenance-firmware", "Firmware navigation targets Maintenance firmware.");
Require(nameof(NetworkHealthViewInput.RouterFirmwareVersion) == "RouterFirmwareVersion", "Network Health has no LuCI firmware input.");
using ServiceProvider services = new ServiceCollection().AddSingleton<DashboardViewModel>().BuildServiceProvider();
Require(ReferenceEquals(services.GetRequiredService<DashboardViewModel>(), services.GetRequiredService<DashboardViewModel>()), "Dashboard ViewModel DI registration must be authoritative.");

using PublicIpService publicIp = new();
List<(string? Previous, string Current)> publicIpEvents = [];
publicIp.PublicIpChanged += (previous, current) => publicIpEvents.Add((previous, current));
MethodInfo? publish = typeof(PublicIpService).GetMethod("Publish", BindingFlags.Instance | BindingFlags.NonPublic);
Require(publish is not null, "Public-IP publisher is available for deterministic change detection coverage.");
publish!.Invoke(publicIp, [new PublicIpResult(" 1.2.3.4 ", DateTimeOffset.UtcNow, PublicIpStatus.Available, null)]);
Require(publicIpEvents.Count == 0, "first confirmed public IP establishes a silent baseline");
publish.Invoke(publicIp, [new PublicIpResult("1.2.3.4", DateTimeOffset.UtcNow, PublicIpStatus.Available, null)]);
Require(publicIpEvents.Count == 0, "normalized unchanged public IP does not raise an event");
publish.Invoke(publicIp, [new PublicIpResult(null, DateTimeOffset.UtcNow, PublicIpStatus.Unavailable, null)]);
publish.Invoke(publicIp, [new PublicIpResult("1.2.3.4", DateTimeOffset.UtcNow, PublicIpStatus.Available, null)]);
Require(publicIpEvents.Count == 0, "unavailable then unchanged public IP does not raise an event");
publish.Invoke(publicIp, [new PublicIpResult("5.6.7.8", DateTimeOffset.UtcNow, PublicIpStatus.Available, null)]);
Require(publicIpEvents.Count == 1, "a confirmed public IP transition raises one event");
Require(publicIpEvents[0] == ("1.2.3.4", "5.6.7.8"), "public IP event compares confirmed normalized values");

MethodInfo? automaticUpdateDue = typeof(UpdateService).GetMethod("IsAutomaticCheckDue", BindingFlags.Static | BindingFlags.NonPublic);
Require(automaticUpdateDue is not null, "automatic update due policy is available for deterministic coverage");
DateTimeOffset updateNow = DateTimeOffset.UtcNow;
Require((bool)automaticUpdateDue!.Invoke(null, [new AppSettings(), updateNow])!, "first automatic update check is due");
Require(!(bool)automaticUpdateDue.Invoke(null, [new AppSettings { LastSuccessfulUpdateCheckUtc = updateNow - TimeSpan.FromHours(23) }, updateNow])!, "automatic update check is skipped before 24 hours");
Require((bool)automaticUpdateDue.Invoke(null, [new AppSettings { LastSuccessfulUpdateCheckUtc = updateNow - TimeSpan.FromHours(25) }, updateNow])!, "automatic update check is due after 24 hours");
Console.WriteLine("Network Health projection fixtures passed: 43/43.");
